### ISSUE TITLE
Assigned Training Link is ignoring Survey Type Selected

### ISSUE THREAD

**Issue by dataCollegechurch** [BEMADEV/Ministry-Safe#5] opened 2023-12-05 20:54 UTC
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Our team currently has a need to assign the skillful screening training to some users. When I select "Skillful Screening Training" as the survey type the user is assigned "Standard Sexual Abuse Awareness Training" instead of Skillful Screening Training".

### Expected Behavior

User will be assigned the training that matches the Survey Type selected in the Initial Request Get Details Action of the workflow.

### Actual Behavior

The direct login url assigned brings the user to Standard Sexual Abuse Awareness Training when clicked.

### Steps to Reproduce

1) Navigate to a user profile
2) Click Actions then launch the workflow to assign the training
3) Change the Survey Type Value to "Skillful Screening Training"
4) Click Submit
5) In the email received by the user, click the training link/button

### Rock Version

16.0

### Plugin Version

1.12.6.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment] 2024-01-23 14:41
Hi @dataCollegechurch ! Digging into this, the link in the email logs them in and plops them onto a landing page with any required trainings front and center, but doesn't pass in a survey type on its own, just a user identifier. Testing locally, I wasn't able to replicate this, so I suspect the issue is occurring when trying to assign the training (i.e. Rock is accidentally telling MinistrySafe to assign a Standard training to them). Can you confirm your training type codes look like this? Additionally, when you go into Ministry Safe, what trainings are assigned to the user?
![image](https://github.com/BEMADEV/Ministry-Safe/assets/5482014/901658c1-7cf9-4038-98e1-f238066d08f6)

**Comment by dataCollegechurch** [comment] 2024-01-23 18:48
Hi Taylor, I was able to confirm that my initial description of the bug was inaccurate. It would be more clearly stated that when multiple trainings are assigned to one user, the landing page generated default's to opening the Sexual Abuse Awareness training. I am happy to schedule a quick zoom with you to show you what I am seeing.

**Comment by tcavaletto** [comment] 2024-05-17 15:24
So we just send a link to MinistrySafe that passes in the user id, so if you want to be able to show a specific training, that would be a feature request you need to reach out to MinistrySafe to do since it's on their side of things.

**Closed as completed by tcavaletto** 2024-05-17 15:24 UTC
Labels: bug

**Comment by dataCollegechurch** [comment] 2024-06-07 22:54
Hi Taylor,

It looks like this is already possible if you pass in a survey_type url parameter and value:

For example this works with the peer-to-peer training

https://safetysystem.abusepreventionsystems.com/trainings/quiz?survey_type=peer_to_peer_training&t=userid

I will reach out to MinistrySafe and confirm.

~Tony

________________________________

**Comment by dataCollegechurch** [comment] 2024-06-10 22:54
Is there a technical reason you couldn't instead generate a link that follow this format?:

https://safetysystem.abusepreventionsystems.com/trainings/quiz?survey_type=peer_to_peer_training&t=trainingguid
________________________________

**Comment by dataCollegechurch** [comment] 2024-06-12 20:05
MinistrySafe said they will reach out to you regarding this request, can you let me know when they do?

**Comment by dataCollegechurch** [comment] 2024-09-09 14:21
@tcavaletto - Has Ministrysafe reached out to discuss this request?
